# okay here is the thing, config folder dont work at the moment for themes

# if i use mount i need to mount layout and co as well as well
module:
  mounts:
    - source: layouts
      target: layouts
    - source: assets
      target: assets
    - source: static
      target: static
    - source: i18n
      target: i18n
    - source: node_modules
      target: assets/vendorlibs
  hugoVersion:
    extended: true

sitemap:
  changefreq: weekly
  disable: false
  priority: 0.8

enableRobotsTXT: true

# sectionPagesMenu: main