name = "stargazer-layout"
license = "MIT"
licenselink = "https://github.com/Blackstareye/stargazer-layout/LICENSE"
description = """Stargazer Layout is a hugo theme module that uses beer 
css for styling and supports node_modules
and importmaps. It offers features like minification, fingerprinting,
and custom JS/CSS integration.

See more in the README
"""

# The home page of the theme, where the source can be found
homepage = "https://github.com/Blackstareye/stargazer-layout"

# If you have a running demo of the theme
demosite = "https://blackstareye.github.io/stargazer-layout/"

# Taxonomy terms
tags = ["blog", "dark", "responsive", ]
features = ["minify", "fingerprint", "node-modules", "beercss", "material-3", "material", "darkmode", "custom-color", "color", "responsive", "importmap", "pagination"]

# If the theme has a single author
[author]
  name=  "Blackeye"
  homepage=  "https://github.com/Blackstareye/"

[module]
  [module.hugoVersion]
    extended= true
    hugoVersion=
